name: log_viewer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  fluent_ui: ^4.12.0
  bitsdojo_window: ^0.1.6
  flutter_acrylic: ^1.1.4
  scaled_app: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/example.log
    - assets/background_blue.png
    - assets/background_red.png